services:
  spotdl-bot:
    image: mralexsaavedra/spotdl-bot:latest
    container_name: spotdl-bot
    volumes:
      - ./music:/music # CAMBIA ESTA RUTA A TU DIRECTORIO DE MÚSICA
      - ./spotdl-bot/data:/root/.spotdl/.spotipy # CAMBIA ESTA RUTA A TU DIRECTORIO
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_ADMIN=${TELEGRAM_ADMIN}
      - CONTAINER_NAME=spotdl-bot
      - TZ=Europe/Madrid
      - LANGUAGE=ES
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    env_file:
      - .env
    restart: unless-stopped