name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag
        id: release_tag
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}
          TAG=${RAW_TAG#v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spotdl-bot:${{ steps.release_tag.outputs.tag }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/spotdl-bot:${{ steps.release_tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/spotdl-bot:latest

      - name: Push Docker image (version)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spotdl-bot:${{ steps.release_tag.outputs.tag }}

      - name: Push Docker image (latest)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spotdl-bot:latest
